make:
	g++ Car1.cpp -o grafika9 -lGL -lGLU -lglut -Wall

shader:
	g++ Car2.cpp -o grafika9Shader -lGL -lGLU -lglut -Wall -lGLEW

run :
	./grafika9

run-shader:
	./grafika9Shader

clean :
	rm -rf grafika9
